### ISSUE TITLE
IaC to deploy Nutanix VMs

### ISSUE THREAD

**Issue by mjnagel** [defenseunicorns/delivery-nutanix-iac#3]
To allow DUBBD deployments on-prem in Nutanix environments we should create IaC module(s) to handle creation of VMs on Nutanix (with applicable storage, networking, etc). This ticket assumes bare metal machine(s) exist, pre-provisioned with the Nutanix hypervisor.

Requirements:
- VMs should use the image from https://github.com/defenseunicorns/uds-rke2-image-builder by default
- VMs should have an opinionated configuration by default
- All storage and networking requirements satisfied for the VMs to network together
- Terraform should be used

```[tasklist]
### Tasks
- [x] Repo created for IaC
- [x] Terraform module(s) created to provision VMs
- [ ] Terraform module(s) created to provision networking
- [ ] Documented usage of terraform to handle VM creation
```

**Comment by mjnagel** [comment]
Closing this out as the initial IaC is in place. Follow on changes based on delivery needs will be tracked separately.
